### PR TITLE
Moving create_ns outside of eval + fix unwanted namespace creation

### PR DESCRIPTION
**Pull request by Typositoire**
Fixes https://github.com/rimusz/helm-tiller/issues/45

Also some cleanup from my previous PR. After some thoughts `create_ns` should not have been inside the `eval` statement.

### CODE REVIEW

**Comment by rimusz** [comment]
shall we set `${CREATE_NAMESPACE_IF_MISSING}" == "false"`?
also please bump plugin version, and thanks for the PR 👍

**Comment by Typositoire** [comment]
oh yeah sorry the version.

By default you mean? Or just as a fix to not create namespace when doing `helm list` ?

**Comment by rimusz** [comment]
if the namespace is provided we should create it if there is no such one, otherwise even `helm list` will fail

**Comment by Typositoire** [comment]
Helm list doesn't fail when NS doesn't exist.

image

**Comment by rimusz** [comment]
but then it shows an empty list, ideally it should create the namespace if you set it

**Comment by Typositoire** [comment]
Here's an example, I have 2 cluster. And I though that one app was installed on both because I did a list on a namespace that wasn't supposed to exist on ClusterA. it just pollute the namespace list for no reason.

Why does an empty list matter ? Am I missing something? There's no helm release in the namespace to me an empty list is a valid result.

**Comment by rimusz** [comment]
a valid point as well :)
ok, bump the plugin version and I will release it

**Pull request merged**
